/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated from configure.in by autoheader.  */
/* Define if you havnt socklen_t type */
/* #undef socklen_t */

/* Define if you want to use LDAP */
/* #undef HAVE_LDAP */

/* Define if filesystem /proc exists */
#define HAVE_PROC 1

/* Define if sys/resource.h has function setpriority() */
#define HAVE_SYS_RESOURCE_SETPRIORITY 1

/* Define if file /proc/net/dev exists */
/* #undef HAVE_PROC_NET_DEV */

/* Define if file /proc/loadavg exists */
/* #undef HAVE_PROC_LOADAVG */

/* Define if function sysconf is in unistd.h */
#define HAVE_UNISTD_SYSCONF 1

/* Define if function va_copy is in stdarg.h */
#define HAVE___VA_COPY 1

/* Define if function sysctl accepts KERN_BOOTTIME */
/* #undef HAVE_FUNCTION_SYSCTL_KERN_BOOTTIME */

/* Define if function sysctl accepts KERN_MAXPROC */
/* #undef HAVE_FUNCTION_SYSCTL_KERN_MAXPROC */

/* Define if function sysctl accepts KERN_MAXFILES */
/* #undef HAVE_FUNCTION_SYSCTL_KERN_MAXFILES */

/* Define if function setproctitle() exists */
/* #undef HAVE_FUNCTION_SETPROCTITLE */

/* Define if functions seteuid() and setegid() exist */
#define HAVE_FUNCTION_SETEUID 1

/* Define if file /proc/1/status exists */
#define HAVE_PROC_1_STATUS 1

/* Define if file /proc/0/psinfo exists */
#define HAVE_PROC_0_PSINFO 1

/* Define if sys/swap.h defines struct swaptable*/
#define HAVE_SYS_SWAP_SWAPTABLE 1

/* Define if sys/vmmeter.h defines struct vmtotal*/
/* #undef HAVE_SYS_VMMETER_VMTOTAL */

/* Define if structure sysinfo has mem_unit */
/* #undef HAVE_SYSINFO_MEM_UNIT */

/* Define if structure sysinfo has bufferram */
/* #undef HAVE_SYSINFO_BUFFERRAM */

/* Define if structure sysinfo has procs */
/* #undef HAVE_SYSINFO_PROCS */

/* Define if structure sysinfo has uptime */
/* #undef HAVE_SYSINFO_UPTIME */

/* Define if structure sysinfo has bufferram */
/* #undef HAVE_SYSINFO_FREERAM */

/* Define if structure sysinfo has sharedram */
/* #undef HAVE_SYSINFO_SHAREDRAM */

/* Define if structure sysinfo has totalram */
/* #undef HAVE_SYSINFO_TOTALRAM */

/* Define if structure sysinfo has totalswap */
/* #undef HAVE_SYSINFO_TOTALSWAP */

/* Define if structure sysinfo has freeswap */
/* #undef HAVE_SYSINFO_FREESWAP */

/* Define if you want to use MySQL */
#define HAVE_MYSQL 1

/* Define if you want to use PostgreSQL */
/* #undef HAVE_PGSQL */

/* Define if you want to use SNMP */
#define HAVE_SNMP 1

/* Define if you want to use NET-SNMP */
#define HAVE_NETSNMP 1

/* Define if you want to use UCD-SNMP */
/* #undef HAVE_UCDSNMP */

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the `asprintf' function. */
/* #undef HAVE_ASPRINTF */

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `getloadavg' function. */
#define HAVE_GETLOADAVG 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <kstat.h> header file. */
#define HAVE_KSTAT_H 1

/* Define to 1 if you have the `kstat' library (-lkstat). */
#define HAVE_LIBKSTAT 1

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `socket' library (-lsocket). */
#define HAVE_LIBSOCKET 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <mtent.h> header file. */
/* #undef HAVE_MTENT_H */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strtod' function. */
#define HAVE_STRTOD 1

/* Define to 1 if you have the <syslog.h> header file. */
#define HAVE_SYSLOG_H 1

/* Define to 1 if you have the <sys/loadavg.h> header file. */
#define HAVE_SYS_LOADAVG_H 1

/* Define to 1 if you have the <sys/mount.h> header file. */
#define HAVE_SYS_MOUNT_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/procfs.h> header file. */
#define HAVE_SYS_PROCFS_H 1

/* Define to 1 if you have the <sys/pstat.h> header file. */
/* #undef HAVE_SYS_PSTAT_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/statvfs.h> header file. */
#define HAVE_SYS_STATVFS_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/swap.h> header file. */
#define HAVE_SYS_SWAP_H 1

/* Define to 1 if you have the <sys/syscall.h> header file. */
#define HAVE_SYS_SYSCALL_H 1

/* Define to 1 if you have the <sys/sysctl.h> header file. */
/* #undef HAVE_SYS_SYSCTL_H */

/* Define to 1 if you have the <sys/sysinfo.h> header file. */
#define HAVE_SYS_SYSINFO_H 1

/* Define to 1 if you have the <sys/sysmacros.h> header file. */
#define HAVE_SYS_SYSMACROS_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/vfs.h> header file. */
#define HAVE_SYS_VFS_H 1

/* Define to 1 if you have the <sys/vmmeter.h> header file. */
#define HAVE_SYS_VMMETER_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vasprintf' function. */
/* #undef HAVE_VASPRINTF */

/* Define to 1 if you have the <vm/vm_param.h> header file. */
/* #undef HAVE_VM_VM_PARAM_H */

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */
